// Code generated by MockGen. DO NOT EDIT.
// Source: aws/iface/autoscaling_IF.go

// Package mock_aws is a generated GoMock package.
package mock_aws

import (
	session "github.com/aws/aws-sdk-go/aws/session"
	autoscaling "github.com/aws/aws-sdk-go/service/autoscaling"
	gomock "github.com/golang/mock/gomock"
	iface "github.com/thomasobenaus/sokar/aws/iface"
	reflect "reflect"
)

// MockAutoScaling is a mock of AutoScaling interface
type MockAutoScaling struct {
	ctrl     *gomock.Controller
	recorder *MockAutoScalingMockRecorder
}

// MockAutoScalingMockRecorder is the mock recorder for MockAutoScaling
type MockAutoScalingMockRecorder struct {
	mock *MockAutoScaling
}

// NewMockAutoScaling creates a new mock instance
func NewMockAutoScaling(ctrl *gomock.Controller) *MockAutoScaling {
	mock := &MockAutoScaling{ctrl: ctrl}
	mock.recorder = &MockAutoScalingMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockAutoScaling) EXPECT() *MockAutoScalingMockRecorder {
	return m.recorder
}

// DescribeAutoScalingGroups mocks base method
func (m *MockAutoScaling) DescribeAutoScalingGroups(input *autoscaling.DescribeAutoScalingGroupsInput) (*autoscaling.DescribeAutoScalingGroupsOutput, error) {
	ret := m.ctrl.Call(m, "DescribeAutoScalingGroups", input)
	ret0, _ := ret[0].(*autoscaling.DescribeAutoScalingGroupsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DescribeAutoScalingGroups indicates an expected call of DescribeAutoScalingGroups
func (mr *MockAutoScalingMockRecorder) DescribeAutoScalingGroups(input interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeAutoScalingGroups", reflect.TypeOf((*MockAutoScaling)(nil).DescribeAutoScalingGroups), input)
}

// UpdateAutoScalingGroup mocks base method
func (m *MockAutoScaling) UpdateAutoScalingGroup(input *autoscaling.UpdateAutoScalingGroupInput) (*autoscaling.UpdateAutoScalingGroupOutput, error) {
	ret := m.ctrl.Call(m, "UpdateAutoScalingGroup", input)
	ret0, _ := ret[0].(*autoscaling.UpdateAutoScalingGroupOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateAutoScalingGroup indicates an expected call of UpdateAutoScalingGroup
func (mr *MockAutoScalingMockRecorder) UpdateAutoScalingGroup(input interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAutoScalingGroup", reflect.TypeOf((*MockAutoScaling)(nil).UpdateAutoScalingGroup), input)
}

// MockAutoScalingFactory is a mock of AutoScalingFactory interface
type MockAutoScalingFactory struct {
	ctrl     *gomock.Controller
	recorder *MockAutoScalingFactoryMockRecorder
}

// MockAutoScalingFactoryMockRecorder is the mock recorder for MockAutoScalingFactory
type MockAutoScalingFactoryMockRecorder struct {
	mock *MockAutoScalingFactory
}

// NewMockAutoScalingFactory creates a new mock instance
func NewMockAutoScalingFactory(ctrl *gomock.Controller) *MockAutoScalingFactory {
	mock := &MockAutoScalingFactory{ctrl: ctrl}
	mock.recorder = &MockAutoScalingFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockAutoScalingFactory) EXPECT() *MockAutoScalingFactoryMockRecorder {
	return m.recorder
}

// CreateAutoScaling mocks base method
func (m *MockAutoScalingFactory) CreateAutoScaling(session *session.Session) iface.AutoScaling {
	ret := m.ctrl.Call(m, "CreateAutoScaling", session)
	ret0, _ := ret[0].(iface.AutoScaling)
	return ret0
}

// CreateAutoScaling indicates an expected call of CreateAutoScaling
func (mr *MockAutoScalingFactoryMockRecorder) CreateAutoScaling(session interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAutoScaling", reflect.TypeOf((*MockAutoScalingFactory)(nil).CreateAutoScaling), session)
}
