// Code generated by MockGen. DO NOT EDIT.
// Source: aws/iface/autoscaling_IF.go

// Package mock_aws is a generated GoMock package.
package mock_aws

import (
	reflect "reflect"

	request "github.com/aws/aws-sdk-go/aws/request"
	session "github.com/aws/aws-sdk-go/aws/session"
	autoscaling "github.com/aws/aws-sdk-go/service/autoscaling"
	gomock "github.com/golang/mock/gomock"
	aws "github.com/thomasobenaus/sokar/aws/iface"
)

// MockAutoScaling is a mock of AutoScaling interface.
type MockAutoScaling struct {
	ctrl     *gomock.Controller
	recorder *MockAutoScalingMockRecorder
}

// MockAutoScalingMockRecorder is the mock recorder for MockAutoScaling.
type MockAutoScalingMockRecorder struct {
	mock *MockAutoScaling
}

// NewMockAutoScaling creates a new mock instance.
func NewMockAutoScaling(ctrl *gomock.Controller) *MockAutoScaling {
	mock := &MockAutoScaling{ctrl: ctrl}
	mock.recorder = &MockAutoScalingMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAutoScaling) EXPECT() *MockAutoScalingMockRecorder {
	return m.recorder
}

// DescribeAutoScalingGroups mocks base method.
func (m *MockAutoScaling) DescribeAutoScalingGroups(input *autoscaling.DescribeAutoScalingGroupsInput) (*autoscaling.DescribeAutoScalingGroupsOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DescribeAutoScalingGroups", input)
	ret0, _ := ret[0].(*autoscaling.DescribeAutoScalingGroupsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DescribeAutoScalingGroups indicates an expected call of DescribeAutoScalingGroups.
func (mr *MockAutoScalingMockRecorder) DescribeAutoScalingGroups(input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeAutoScalingGroups", reflect.TypeOf((*MockAutoScaling)(nil).DescribeAutoScalingGroups), input)
}

// DescribeScalingActivitiesRequest mocks base method.
func (m *MockAutoScaling) DescribeScalingActivitiesRequest(input *autoscaling.DescribeScalingActivitiesInput) (*request.Request, *autoscaling.DescribeScalingActivitiesOutput) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DescribeScalingActivitiesRequest", input)
	ret0, _ := ret[0].(*request.Request)
	ret1, _ := ret[1].(*autoscaling.DescribeScalingActivitiesOutput)
	return ret0, ret1
}

// DescribeScalingActivitiesRequest indicates an expected call of DescribeScalingActivitiesRequest.
func (mr *MockAutoScalingMockRecorder) DescribeScalingActivitiesRequest(input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeScalingActivitiesRequest", reflect.TypeOf((*MockAutoScaling)(nil).DescribeScalingActivitiesRequest), input)
}

// TerminateInstanceInAutoScalingGroupRequest mocks base method.
func (m *MockAutoScaling) TerminateInstanceInAutoScalingGroupRequest(input *autoscaling.TerminateInstanceInAutoScalingGroupInput) (*request.Request, *autoscaling.TerminateInstanceInAutoScalingGroupOutput) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TerminateInstanceInAutoScalingGroupRequest", input)
	ret0, _ := ret[0].(*request.Request)
	ret1, _ := ret[1].(*autoscaling.TerminateInstanceInAutoScalingGroupOutput)
	return ret0, ret1
}

// TerminateInstanceInAutoScalingGroupRequest indicates an expected call of TerminateInstanceInAutoScalingGroupRequest.
func (mr *MockAutoScalingMockRecorder) TerminateInstanceInAutoScalingGroupRequest(input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TerminateInstanceInAutoScalingGroupRequest", reflect.TypeOf((*MockAutoScaling)(nil).TerminateInstanceInAutoScalingGroupRequest), input)
}

// UpdateAutoScalingGroup mocks base method.
func (m *MockAutoScaling) UpdateAutoScalingGroup(input *autoscaling.UpdateAutoScalingGroupInput) (*autoscaling.UpdateAutoScalingGroupOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAutoScalingGroup", input)
	ret0, _ := ret[0].(*autoscaling.UpdateAutoScalingGroupOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateAutoScalingGroup indicates an expected call of UpdateAutoScalingGroup.
func (mr *MockAutoScalingMockRecorder) UpdateAutoScalingGroup(input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAutoScalingGroup", reflect.TypeOf((*MockAutoScaling)(nil).UpdateAutoScalingGroup), input)
}

// MockAutoScalingFactory is a mock of AutoScalingFactory interface.
type MockAutoScalingFactory struct {
	ctrl     *gomock.Controller
	recorder *MockAutoScalingFactoryMockRecorder
}

// MockAutoScalingFactoryMockRecorder is the mock recorder for MockAutoScalingFactory.
type MockAutoScalingFactoryMockRecorder struct {
	mock *MockAutoScalingFactory
}

// NewMockAutoScalingFactory creates a new mock instance.
func NewMockAutoScalingFactory(ctrl *gomock.Controller) *MockAutoScalingFactory {
	mock := &MockAutoScalingFactory{ctrl: ctrl}
	mock.recorder = &MockAutoScalingFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAutoScalingFactory) EXPECT() *MockAutoScalingFactoryMockRecorder {
	return m.recorder
}

// CreateAutoScaling mocks base method.
func (m *MockAutoScalingFactory) CreateAutoScaling(session *session.Session) aws.AutoScaling {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAutoScaling", session)
	ret0, _ := ret[0].(aws.AutoScaling)
	return ret0
}

// CreateAutoScaling indicates an expected call of CreateAutoScaling.
func (mr *MockAutoScalingFactoryMockRecorder) CreateAutoScaling(session interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAutoScaling", reflect.TypeOf((*MockAutoScalingFactory)(nil).CreateAutoScaling), session)
}
