// Code generated by MockGen. DO NOT EDIT.
// Source: nomadWorker/awsAsg_IF.go

// Package mock_nomadWorker is a generated GoMock package.
package mock_nomadWorker

import (
	autoscaling "github.com/aws/aws-sdk-go/service/autoscaling"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockAutoScaling is a mock of AutoScaling interface
type MockAutoScaling struct {
	ctrl     *gomock.Controller
	recorder *MockAutoScalingMockRecorder
}

// MockAutoScalingMockRecorder is the mock recorder for MockAutoScaling
type MockAutoScalingMockRecorder struct {
	mock *MockAutoScaling
}

// NewMockAutoScaling creates a new mock instance
func NewMockAutoScaling(ctrl *gomock.Controller) *MockAutoScaling {
	mock := &MockAutoScaling{ctrl: ctrl}
	mock.recorder = &MockAutoScalingMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockAutoScaling) EXPECT() *MockAutoScalingMockRecorder {
	return m.recorder
}

// DescribeAutoScalingGroups mocks base method
func (m *MockAutoScaling) DescribeAutoScalingGroups(input *autoscaling.DescribeAutoScalingGroupsInput) (*autoscaling.DescribeAutoScalingGroupsOutput, error) {
	ret := m.ctrl.Call(m, "DescribeAutoScalingGroups", input)
	ret0, _ := ret[0].(*autoscaling.DescribeAutoScalingGroupsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DescribeAutoScalingGroups indicates an expected call of DescribeAutoScalingGroups
func (mr *MockAutoScalingMockRecorder) DescribeAutoScalingGroups(input interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeAutoScalingGroups", reflect.TypeOf((*MockAutoScaling)(nil).DescribeAutoScalingGroups), input)
}
