// Code generated by MockGen. DO NOT EDIT.
// Source: scaler/scalingtarget_IF.go

// Package mock_scaler is a generated GoMock package.
package mock_scaler

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockScalingTarget is a mock of ScalingTarget interface
type MockScalingTarget struct {
	ctrl     *gomock.Controller
	recorder *MockScalingTargetMockRecorder
}

// MockScalingTargetMockRecorder is the mock recorder for MockScalingTarget
type MockScalingTargetMockRecorder struct {
	mock *MockScalingTarget
}

// NewMockScalingTarget creates a new mock instance
func NewMockScalingTarget(ctrl *gomock.Controller) *MockScalingTarget {
	mock := &MockScalingTarget{ctrl: ctrl}
	mock.recorder = &MockScalingTargetMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockScalingTarget) EXPECT() *MockScalingTargetMockRecorder {
	return m.recorder
}

// SetJobCount mocks base method
func (m *MockScalingTarget) SetJobCount(jobname string, count uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetJobCount", jobname, count)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetJobCount indicates an expected call of SetJobCount
func (mr *MockScalingTargetMockRecorder) SetJobCount(jobname, count interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetJobCount", reflect.TypeOf((*MockScalingTarget)(nil).SetJobCount), jobname, count)
}

// GetJobCount mocks base method
func (m *MockScalingTarget) GetJobCount(jobname string) (uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJobCount", jobname)
	ret0, _ := ret[0].(uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetJobCount indicates an expected call of GetJobCount
func (mr *MockScalingTargetMockRecorder) GetJobCount(jobname interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJobCount", reflect.TypeOf((*MockScalingTarget)(nil).GetJobCount), jobname)
}

// IsJobDead mocks base method
func (m *MockScalingTarget) IsJobDead(jobname string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsJobDead", jobname)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsJobDead indicates an expected call of IsJobDead
func (mr *MockScalingTargetMockRecorder) IsJobDead(jobname interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsJobDead", reflect.TypeOf((*MockScalingTarget)(nil).IsJobDead), jobname)
}
