{
 "title": "Sokar",
 "tags": [ "sokar" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "interval", "label": "interval", "query": "1m,2m,5m,10m,30m,1h,2h,5h,10h" }
  ]
 },
 "panels": [
  {
   "title": "Current vs Planned Count ",
   "type": "graph",
   "description": "Shows the relation between the currently deployed and the planned number of instances.\n\nNotice: Current and Planned Count are measured **before** the scale action took place. Thus the current count reflects the state without the applied desired/ planned count.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sokar_cap_pre_scale_job_count", "legendFormat": "PreScale Count" },
    { "expr": "sokar_cap_planned_job_count", "legendFormat": "Planned Count" },
    { "expr": "sokar_cap_scale_factor", "legendFormat": "Scale Factor" }
   ]
  },
  {
   "title": "Scale Actions (in last $interval)",
   "type": "graph",
   "description": "For each ScaleEvent sokar tries to scale the target.\n\nThis panel shows the number of failed and successful scale actions. A failed scale action can be caused by the fact that the scaler rejected the request to scale since the min/max bound of the target count is already reached.\n",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(sokar_scale_events_total[$interval]) - increase(sokar_failed_scaling_total[$interval])",
     "legendFormat": "Successful Scale Actions"
    },
    {
     "expr": "increase(sokar_failed_scaling_total[$interval])",
     "legendFormat": "Failed Scale Actions"
    },
    {
     "expr": "increase(sokar_cap_skipped_scaling_during_cooldown_total[$interval])",
     "legendFormat": "Skipped Scale Actions (during cooldown)"
    }
   ]
  },
  {
   "title": "Planned (skipped) Scaling Actions",
   "type": "graph",
   "description": "Shows if there are currently scaling actions that where planned by sokar but not executed due to dry run mode.",
   "gridPos": { "h": 6, "w": 23, "x": 1, "y": 17 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sokar_planned_but_skipped_scaling",
     "legendFormat": "Planned '{{direction}}' scaling"
    }
   ]
  }
 ]
}