{
 "title": "Scaler",
 "tags": [ "sokar" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "interval", "label": "interval", "query": "30s,1m,2m,5m,10m,30m,1h" }
  ]
 },
 "panels": [
  {
   "title": "Scale Tickets (in last $interval)",
   "type": "graph",
   "description": "Shows the added/ applied/ rejected Scale Tickets in last $interval.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(sokar_sca_scaling_ticket_counter[$interval])",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Scaling Duration (in $interval)",
   "type": "heatmap",
   "description": "Shows the time it takes to apply a scaling action.",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(sokar_sca_scaling_duration_seconds_bucket[$interval])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Scale Resuls (in last $interval)",
   "type": "graph",
   "description": "Shows the result of the scaling actions (done,failed, ignored).\nAdditionally occurrences are shown when the scaling policy was violated.",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(sokar_sca_scale_result_counter[$interval])",
     "legendFormat": "{{result}}"
    },
    {
     "expr": "increase(sokar_sca_scaling_policy_violated[$interval])",
     "legendFormat": "Scale Policy - {{threshold}}"
    }
   ]
  }
 ]
}