{
 "title": "Sokar",
 "tags": [ "sokar" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "interval", "label": "interval", "query": "1m,2m,5m,10m,30m,1h,2h,5h,10h" }
  ]
 },
 "panels": [
  {
   "title": "Scale Actions",
   "type": "graph",
   "description": "For each ScaleEvent sokar tries to scale the target.\n\nThis panel shows the number of failed and successful scale actions. A failed scale action can be caused by the fact that the scaler rejected the request to scale since the min/max bound of the target count is already reached.\n",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(sokar_scale_events_total[$interval]) - increase(sokar_failed_scaling_total[$interval])",
     "legendFormat": "Successful Scale Actions"
    },
    {
     "expr": "increase(sokar_failed_scaling_total[$interval])",
     "legendFormat": "Failed Scale Actions"
    },
    { "expr": "sokar_planned_count", "legendFormat": "Planned Count" }
   ]
  },
  {
   "title": "ScaleCounter",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sokar_saa_scale_counter", "legendFormat": "ScaleCounter" },
    { "expr": "sokar_saa_scale_factor", "legendFormat": "ScaleFactor" }
   ]
  },
  {
   "title": "ScaleAlerts",
   "type": "graph",
   "description": "Shows the number of currently active Up/Down alerts.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sokar_saa_alerts_total", "legendFormat": "{{direction}}" }
   ]
  }
 ]
}