{
 "title": "ScaleAlertAggregator",
 "tags": [ "sokar" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "interval", "label": "interval", "query": "10s,30s,1m,2m,5m,10m,30m,1h" }
  ]
 },
 "panels": [
  {
   "title": "Scale Events",
   "type": "graph",
   "description": "Shows the UP/DOWN ScaleEvents triggered by the SAA.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(sokar_saa_scale_event_counter[$interval])",
     "legendFormat": "{{direction}}"
    }
   ]
  },
  {
   "title": "ScaleCounter",
   "type": "graph",
   "description": "Shows the current ScaleCounter and the ScaleFactor that is the according gradient.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sokar_saa_scale_counter", "legendFormat": "ScaleCounter" },
    { "expr": "sokar_saa_scale_factor", "legendFormat": "ScaleFactor" }
   ]
  },
  {
   "title": "ScaleAlerts",
   "type": "graph",
   "description": "Shows the number of currently active Up/Down alerts.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sokar_saa_alerts_total", "legendFormat": "{{direction}}" }
   ]
  }
 ]
}